/** Isolated shadcn-backed Desktop dialog rendered as a modal BrowserWindow. */

import { BrowserWindow } from 'electron'
import type { MessageBoxOptions, MessageBoxReturnValue } from 'electron'
import { fileURLToPath } from 'node:url'
import {
  auxiliaryWindowChromeOptions,
  auxiliaryWindowHasCustomFrame,
} from './auxiliary-window-options.ts'
import { revealApplication } from './electron-reveal.ts'

const DIALOG_SCHEME = 'dsh-desktop-dialog:'
const DIALOG_DOCUMENT = fileURLToPath(new URL('./native-ui/desktop-dialog.html', import.meta.url))
const MAX_BUTTONS = 4
const DIALOG_WIDTH = 480
const DIALOG_INITIAL_HEIGHT = 300
const DIAGNOSTIC_DIALOG_WIDTH = 680
const DIAGNOSTIC_DIALOG_INITIAL_HEIGHT = 460
/** Electron omits the 2rem shadcn action row from the reported preferred height. */
const DIALOG_PREFERRED_HEIGHT_OFFSET = 32
const DIALOG_REVEAL_FALLBACK_MS = 250

export interface DesktopDialogOptions {
  readonly type?: 'none' | 'info' | 'error' | 'question' | 'warning'
  readonly title: string
  readonly message: string
  readonly detail?: string
  readonly buttons: readonly string[]
  readonly defaultId?: number
  readonly cancelId?: number
  /** Use a larger shadcn scroll surface for bounded technical diagnostics. */
  readonly presentation?: 'default' | 'diagnostic'
  /** Override whether this dialog exposes native close/caption controls. */
  readonly windowControls?: boolean
}

export interface DesktopDialogResult {
  readonly response: number
}

function normalizedIndex(value: number | undefined, fallback: number, length: number): number {
  return value !== undefined && Number.isSafeInteger(value) && value >= 0 && value < length
    ? value
    : fallback
}

/** Parse only a bounded response generated by the local dialog document. */
export function parseDesktopDialogResponse(href: string, buttonCount: number): number | undefined {
  let url: URL
  try { url = new URL(href) } catch { return undefined }
  if (url.protocol !== DIALOG_SCHEME || url.hostname !== 'response'
    || url.username !== '' || url.password !== '' || url.port !== ''
    || url.pathname !== '' || url.hash !== ''
    || [...url.searchParams.keys()].some(key => key !== 'id')) return undefined
  const raw = url.searchParams.get('id')
  if (raw === null || !/^(?:0|[1-9]\d*)$/u.test(raw)) return undefined
  const response = Number(raw)
  return Number.isSafeInteger(response) && response >= 0 && response < buttonCount ? response : undefined
}

/** One-shot modal Desktop window; closing it always produces the cancel result. */
export class DesktopDialogWindow {
  constructor(
    private readonly options: DesktopDialogOptions,
    private readonly parent?: BrowserWindow,
  ) {}

  async run(): Promise<DesktopDialogResult> {
    if (this.options.buttons.length === 0 || this.options.buttons.length > MAX_BUTTONS) {
      throw new Error(`dsh-plugin-desktop: Desktop dialog requires 1-${String(MAX_BUTTONS)} buttons`)
    }
    const cancelId = normalizedIndex(this.options.cancelId, this.options.buttons.length - 1, this.options.buttons.length)
    const defaultId = normalizedIndex(this.options.defaultId, 0, this.options.buttons.length)
    const state = Buffer.from(JSON.stringify({
      type: this.options.type ?? 'none',
      title: this.options.title,
      message: this.options.message,
      ...(this.options.detail === undefined ? {} : { detail: this.options.detail }),
      buttons: this.options.buttons,
      defaultId,
      cancelId,
      presentation: this.options.presentation ?? 'default',
    }), 'utf8').toString('base64url')
    const parent = this.parent !== undefined && !this.parent.isDestroyed() ? this.parent : undefined
    // Parented modal dialogs are action surfaces, not independently navigable
    // windows. They stay frameless unless a caller explicitly opts into native
    // controls; standalone notices keep ordinary close controls.
    const windowControls = this.options.windowControls ?? parent === undefined
    const customFrame = auxiliaryWindowHasCustomFrame(process.platform, windowControls)
    const diagnostic = this.options.presentation === 'diagnostic'
    const dialogWidth = diagnostic ? DIAGNOSTIC_DIALOG_WIDTH : DIALOG_WIDTH
    const window = new BrowserWindow({
      title: this.options.title,
      ...auxiliaryWindowChromeOptions(process.platform, windowControls),
      width: dialogWidth,
      height: diagnostic ? DIAGNOSTIC_DIALOG_INITIAL_HEIGHT : DIALOG_INITIAL_HEIGHT,
      useContentSize: true,
      minWidth: diagnostic ? 560 : 420,
      maxWidth: diagnostic ? 860 : 620,
      resizable: windowControls,
      maximizable: false,
      fullscreenable: false,
      show: false,
      autoHideMenuBar: true,
      backgroundColor: '#202124',
      ...(parent === undefined ? {} : { parent, modal: true, skipTaskbar: true }),
      webPreferences: {
        contextIsolation: true,
        nodeIntegration: false,
        nodeIntegrationInSubFrames: false,
        sandbox: true,
        webSecurity: true,
        webviewTag: false,
        spellcheck: false,
        enablePreferredSizeMode: true,
        partition: 'dsh-desktop-dialog',
      },
    })
    window.accessibleTitle = this.options.title
    window.removeMenu()
    window.webContents.setWindowOpenHandler(() => ({ action: 'deny' }))
    window.webContents.on('will-attach-webview', event => { event.preventDefault() })

    return await new Promise<DesktopDialogResult>((resolve, reject) => {
      let settled = false
      let documentLoaded = false
      let paintReady = false
      let layoutReady = false
      let revealed = false
      let preferredHeight: number | undefined
      let appliedHeight: number | undefined
      let revealTimer: ReturnType<typeof setTimeout> | undefined
      const reveal = (): void => {
        if (revealed || !documentLoaded || !paintReady || window.isDestroyed()) return
        revealed = true
        if (revealTimer !== undefined) clearTimeout(revealTimer)
        revealTimer = undefined
        revealApplication(window)
      }
      const finish = (response: number): void => {
        if (settled) return
        settled = true
        if (revealTimer !== undefined) clearTimeout(revealTimer)
        if (!window.isDestroyed()) window.destroy()
        resolve(Object.freeze({ response }))
      }
      const scheduleReveal = (): void => {
        if (!documentLoaded || !paintReady || revealed) return
        if (layoutReady) {
          reveal()
        } else if (revealTimer === undefined) {
          revealTimer = setTimeout(reveal, DIALOG_REVEAL_FALLBACK_MS)
        }
      }
      const applyPreferredSize = (): void => {
        if (!documentLoaded || preferredHeight === undefined || window.isDestroyed()) return
        const height = preferredHeight
        layoutReady = true
        if (height === appliedHeight) {
          scheduleReveal()
          return
        }
        appliedHeight = height
        // Keep this as one content-area resize. On macOS modal sheets the
        // native geometry update can lag this call; reading outer bounds and
        // writing them back immediately can restore the stale, shorter height.
        window.setContentSize(dialogWidth, height, false)
        scheduleReveal()
      }
      const navigate = (event: Electron.Event, href: string): void => {
        event.preventDefault()
        const response = parseDesktopDialogResponse(href, this.options.buttons.length)
        if (response !== undefined) finish(response)
      }
      window.webContents.on('will-navigate', navigate)
      window.webContents.on('will-redirect', navigate)
      window.webContents.on('preferred-size-changed', (_event, size) => {
        if (!Number.isSafeInteger(size.height) || size.height <= 0) return
        preferredHeight = size.height + DIALOG_PREFERRED_HEIGHT_OFFSET
        applyPreferredSize()
      })
      window.webContents.on('did-finish-load', () => {
        documentLoaded = true
        applyPreferredSize()
        scheduleReveal()
      })
      window.once('ready-to-show', () => {
        paintReady = true
        scheduleReveal()
      })
      window.on('closed', () => { finish(cancelId) })
      void window.loadFile(DIALOG_DOCUMENT, {
        query: {
          state,
          platform: process.platform,
          frame: String(customFrame),
        },
      }).catch((cause: unknown) => {
        if (settled) return
        settled = true
        if (revealTimer !== undefined) clearTimeout(revealTimer)
        if (!window.isDestroyed()) window.destroy()
        reject(cause)
      })
    })
  }
}

/** Render a Desktop-level modal window instead of an in-page overlay. */
export async function showDesktopDialog(
  options: DesktopDialogOptions,
  parent?: BrowserWindow,
): Promise<DesktopDialogResult> {
  return await new DesktopDialogWindow(options, parent).run()
}

/** Electron MessageBox-compatible adapter backed by the Desktop dialog window. */
export async function showDesktopMessageBox(
  options: MessageBoxOptions,
  parent?: BrowserWindow,
): Promise<MessageBoxReturnValue> {
  const result = await showDesktopDialog({
    type: options.type ?? 'none',
    title: options.title ?? 'DSH Desktop',
    message: options.message,
    ...(options.detail === undefined ? {} : { detail: options.detail }),
    buttons: options.buttons ?? ['OK'],
    ...(options.defaultId === undefined ? {} : { defaultId: options.defaultId }),
    ...(options.cancelId === undefined ? {} : { cancelId: options.cancelId }),
  }, parent)
  return Object.freeze({ response: result.response, checkboxChecked: false })
}
