/** Isolated pre-Host Setup Wizard window with a strict navigation result channel. */

import { BrowserWindow } from 'electron'
import { fileURLToPath } from 'node:url'
import {
  auxiliaryWindowChromeOptions,
  auxiliaryWindowHasCustomFrame,
} from './auxiliary-window-options.ts'
import { revealApplication } from './electron-reveal.ts'
import type { DesktopLocale } from './runtime.ts'
import {
  desktopSetupWizardSelectionIsAvailable,
  freezeDesktopSetupWizardSelection,
  isDesktopSetupWizardInput,
  type DesktopSetupWizardInput,
  type DesktopSetupWizardMarket,
  type DesktopSetupWizardMode,
  type DesktopSetupWizardNetworkExposure,
  type DesktopSetupWizardResult,
  type DesktopSetupWizardWindowsMaterial,
  type DesktopSetupWizardMacosMaterial,
} from './setup-wizard-contract.ts'
import { desktopSetupWizardCopy } from './setup-wizard-copy.ts'

const SETUP_WIZARD_SCHEME = 'dsh-setup-wizard:'
const SETUP_WIZARD_DOCUMENT = fileURLToPath(new URL('./native-ui/setup-wizard.html', import.meta.url))
const MAX_ACTION_BYTES = 8192
const COMPLETE_KEYS = Object.freeze([
  'mode',
  'macosMaterial',
  'windowsMaterial',
  'openBrowser',
  'networkExposure',
  'market',
  'notificationsEnabled',
  'notifyOnTurnCompletion',
  'notifyOnTurnFailure',
  'notifyOnJobCompletion',
  'notifyOnJobFailure',
] as const)

export interface DesktopSetupWizardWindowOptions {
  readonly locale: DesktopLocale
  readonly input: DesktopSetupWizardInput
}

type DesktopSetupWizardRendererAction = Exclude<DesktopSetupWizardResult, { readonly action: 'quit' }>

function exactBoolean(value: string | null): boolean | undefined {
  if (value === 'true') return true
  if (value === 'false') return false
  return undefined
}

function exactMode(value: string | null): DesktopSetupWizardMode | undefined {
  return value === 'compatibility' || value === 'extended' || value === 'advanced' ? value : undefined
}

function exactMacosMaterial(value: string | null): DesktopSetupWizardMacosMaterial | undefined {
  return value === 'off' || value === 'transparent' ? value : undefined
}

function exactWindowsMaterial(value: string | null): DesktopSetupWizardWindowsMaterial | undefined {
  return value === 'off' || value === 'acrylic' || value === 'mica' ? value : undefined
}

function exactNetworkExposure(value: string | null): DesktopSetupWizardNetworkExposure | undefined {
  return value === 'loopback' || value === 'lan' ? value : undefined
}

function exactMarket(value: string | null): DesktopSetupWizardMarket | undefined {
  return value === 'disabled' || value === 'community-market' || value === 'dsh-market' ? value : undefined
}

/** Parse only a bounded, complete result generated by the local Setup document. */
export function parseDesktopSetupWizardAction(
  href: string,
): DesktopSetupWizardRendererAction | undefined {
  if (new TextEncoder().encode(href).byteLength > MAX_ACTION_BYTES) return undefined
  let url: URL
  try { url = new URL(href) } catch { return undefined }
  if (url.protocol !== SETUP_WIZARD_SCHEME
    || url.username !== '' || url.password !== '' || url.port !== ''
    || url.pathname !== '' || url.hash !== '') return undefined
  const keys = [...url.searchParams.keys()]
  if (url.hostname === 'skip') return keys.length === 0 ? Object.freeze({ action: 'skip' as const }) : undefined
  if (url.hostname !== 'complete'
    || keys.length !== COMPLETE_KEYS.length
    || keys.some(key => !COMPLETE_KEYS.includes(key as typeof COMPLETE_KEYS[number]))
    || COMPLETE_KEYS.some(key => url.searchParams.getAll(key).length !== 1)) return undefined

  const mode = exactMode(url.searchParams.get('mode'))
  const macosMaterial = exactMacosMaterial(url.searchParams.get('macosMaterial'))
  const windowsMaterial = exactWindowsMaterial(url.searchParams.get('windowsMaterial'))
  const openBrowser = exactBoolean(url.searchParams.get('openBrowser'))
  const networkExposure = exactNetworkExposure(url.searchParams.get('networkExposure'))
  const market = exactMarket(url.searchParams.get('market'))
  const enabled = exactBoolean(url.searchParams.get('notificationsEnabled'))
  const notifyOnTurnCompletion = exactBoolean(url.searchParams.get('notifyOnTurnCompletion'))
  const notifyOnTurnFailure = exactBoolean(url.searchParams.get('notifyOnTurnFailure'))
  const notifyOnJobCompletion = exactBoolean(url.searchParams.get('notifyOnJobCompletion'))
  const notifyOnJobFailure = exactBoolean(url.searchParams.get('notifyOnJobFailure'))
  if (mode === undefined || macosMaterial === undefined || windowsMaterial === undefined
    || openBrowser === undefined || networkExposure === undefined || market === undefined
    || enabled === undefined || notifyOnTurnCompletion === undefined
    || notifyOnTurnFailure === undefined || notifyOnJobCompletion === undefined
    || notifyOnJobFailure === undefined) return undefined

  const selection = freezeDesktopSetupWizardSelection({
    mode,
    macosMaterial,
    windowsMaterial,
    openBrowser,
    networkExposure,
    market,
    notifications: {
      enabled,
      notifyOnTurnCompletion,
      notifyOnTurnFailure,
      notifyOnJobCompletion,
      notifyOnJobFailure,
    },
  })
  return Object.freeze({ action: 'complete' as const, selection })
}

/** One-shot native Setup Wizard; close is distinct from the explicit Skip action. */
export class DesktopSetupWizardWindow {
  private started = false
  private window: BrowserWindow | undefined

  constructor(private readonly options: DesktopSetupWizardWindowOptions) {}

  /** Bring the running Wizard forward for app activation and second-instance events. */
  show(): void {
    const window = this.window
    if (window === undefined || window.isDestroyed()) return
    revealApplication(window, this.options.input.platform)
  }

  async run(): Promise<DesktopSetupWizardResult> {
    if (this.started) throw new Error('dsh-plugin-desktop: Setup Wizard can only run once')
    this.started = true
    if (!isDesktopSetupWizardInput(this.options.input)) {
      throw new TypeError('dsh-plugin-desktop: invalid Setup Wizard input')
    }
    const { input } = this.options
    const copy = desktopSetupWizardCopy(this.options.locale)
    const state = Buffer.from(JSON.stringify(input), 'utf8').toString('base64url')
    const customFrame = auxiliaryWindowHasCustomFrame(input.platform)
    const window = new BrowserWindow({
      title: copy.title,
      ...auxiliaryWindowChromeOptions(input.platform),
      width: 880,
      height: 720,
      minWidth: 680,
      minHeight: 560,
      useContentSize: true,
      resizable: true,
      maximizable: false,
      fullscreenable: false,
      // Electron can emit `ready-to-show` before the first hidden Win32 HWND
      // accepts BrowserWindow.show(). Create the local Wizard visibly on
      // Windows so startup never waits behind an unreachable surface.
      show: input.platform === 'win32',
      autoHideMenuBar: true,
      backgroundColor: '#202124',
      webPreferences: {
        contextIsolation: true,
        nodeIntegration: false,
        nodeIntegrationInSubFrames: false,
        sandbox: true,
        webSecurity: true,
        webviewTag: false,
        spellcheck: false,
        partition: 'dsh-setup-wizard',
      },
    })
    this.window = window
    window.accessibleTitle = copy.title
    window.removeMenu()
    window.webContents.setWindowOpenHandler(() => ({ action: 'deny' }))
    window.webContents.on('will-attach-webview', event => { event.preventDefault() })

    return await new Promise<DesktopSetupWizardResult>((resolve, reject) => {
      let settled = false
      const finish = (result: DesktopSetupWizardResult): void => {
        if (settled) return
        settled = true
        if (this.window === window) this.window = undefined
        if (!window.isDestroyed()) window.destroy()
        resolve(result)
      }
      const navigate = (event: Electron.Event, href: string): void => {
        event.preventDefault()
        const action = parseDesktopSetupWizardAction(href)
        if (action === undefined) return
        if (action.action === 'complete'
          && !desktopSetupWizardSelectionIsAvailable(action.selection, input)) return
        finish(action)
      }
      window.webContents.on('will-navigate', navigate)
      window.webContents.on('will-redirect', navigate)
      window.once('ready-to-show', () => {
        if (!settled && this.window === window && !window.isDestroyed()) {
          revealApplication(window, input.platform)
        }
      })
      window.on('closed', () => {
        if (this.window === window) this.window = undefined
        finish(Object.freeze({ action: 'quit' }))
      })
      void window.loadFile(SETUP_WIZARD_DOCUMENT, {
        query: {
          locale: this.options.locale,
          state,
          platform: input.platform,
          frame: String(customFrame),
        },
      }).catch((cause: unknown) => {
        if (settled) return
        settled = true
        if (this.window === window) this.window = undefined
        if (!window.isDestroyed()) window.destroy()
        reject(cause)
      })
    })
  }
}
